# <code>numpy</code>

<b>num</b>erical <b>py</b>thon

- Fast
- Data structures are limited to one data type
- Written in the C programming language

In [29]:
import numpy as np

## Numpy arrays (<code>ndarray</code>)

n-dimensional arrays

## Array Creation

In [30]:
a = np.array([0,1,2])
type(a), a

(numpy.ndarray, array([0, 1, 2]))

In [31]:
np.array((3,4,5))

array([3, 4, 5])

In [32]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(3,7)

array([3, 4, 5, 6])

In [36]:
# format: np.arange([start], stop, [step])
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [38]:
b.dtype

dtype('float64')

In [39]:
c = np.ones((2,3), dtype=np.int64)
c

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [40]:
np.ones((2,3)).astype(np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
d = np.ones((2,3))
print(d.dtype)
d = d.astype(np.int32)
print(d.dtype)

float64
int32


In [42]:
np.full((2,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [43]:
np.identity(6).astype(np.int16)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int16)

In [44]:
d.shape, type(d.shape)

((2, 3), tuple)

In [45]:
# number of rows
d.shape[0]

2

In [46]:
# number of columns
d.shape[1]

3

In [47]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        print(d[i][j])

1
1
1
1
1
1


In [51]:
d.flatten()

array([1, 1, 1, 1, 1, 1])

In [54]:
d.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [56]:
d.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [57]:
np.random.random((2,2))

array([[0.01601558, 0.56409307],
       [0.42340698, 0.7382894 ]])

In [66]:
np.random.randint(0, 9, (2,5))

array([[3, 2, 5, 2, 2],
       [4, 2, 0, 4, 0]])

## numpy Slices and Indexing

In [68]:
h = np.random.random((8,))
h

array([0.09270253, 0.77252393, 0.07615393, 0.10750887, 0.56920686,
       0.44419348, 0.10602389, 0.01271085])

In [71]:
j = np.random.random((7,7))
j

array([[0.84289947, 0.35398689, 0.9551968 , 0.7096073 , 0.13630193,
        0.65978114, 0.19054395],
       [0.4645478 , 0.91883729, 0.46641935, 0.52533993, 0.24641337,
        0.135258  , 0.56032224],
       [0.46924966, 0.01899494, 0.68333358, 0.3740239 , 0.40945611,
        0.65117585, 0.2638785 ],
       [0.66552858, 0.40071934, 0.51337696, 0.62863281, 0.14451895,
        0.93306593, 0.41697164],
       [0.24494242, 0.0845737 , 0.22411413, 0.70108488, 0.08040327,
        0.56551924, 0.58138612],
       [0.90659817, 0.98449794, 0.58519318, 0.12894619, 0.52829803,
        0.88909749, 0.28964525],
       [0.48063969, 0.1655322 , 0.24570394, 0.85272892, 0.31223758,
        0.77380359, 0.80363502]])

In [69]:
type((8,))

tuple

In [70]:
type((8))

int

In [72]:
print(h)
h[1:4]

[0.09270253 0.77252393 0.07615393 0.10750887 0.56920686 0.44419348
 0.10602389 0.01271085]


array([0.77252393, 0.07615393, 0.10750887])

In [75]:
h[1:7:2]

array([0.77252393, 0.10750887, 0.44419348])

SyntaxError: incomplete input (786403058.py, line 1)

In [73]:
j[2][3]

0.3740239015616935

In [74]:
j[2,3]

0.3740239015616935

In [78]:
j[1:6:2, 2]

array([0.46641935, 0.51337696, 0.58519318])

In [79]:
j[1:6, 2:4]

array([[0.46641935, 0.52533993],
       [0.68333358, 0.3740239 ],
       [0.51337696, 0.62863281],
       [0.22411413, 0.70108488],
       [0.58519318, 0.12894619]])

In [80]:
j[[1,2,3], [1,2,3]]

array([0.91883729, 0.68333358, 0.62863281])

## Array Methods and Calcuations

In [81]:
A = np.random.random((3,3))
A

array([[0.68124843, 0.41340898, 0.43512068],
       [0.86116854, 0.43759351, 0.6199251 ],
       [0.62583327, 0.59539012, 0.99054698]])

In [82]:
A.T

array([[0.68124843, 0.86116854, 0.62583327],
       [0.41340898, 0.43759351, 0.59539012],
       [0.43512068, 0.6199251 , 0.99054698]])

In [84]:
np.linalg.trans(A)

AttributeError: module 'numpy.linalg' has no attribute 'trans'

In [85]:
np.linalg.det(A)

-0.04447673974067723

In [88]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.44704045,  3.38231765, -1.48114771],
       [10.45621026, -9.04957473,  1.07046432],
       [-5.3706875 ,  3.30247893,  1.30191465]])

In [89]:
A.dot(Ainv)

array([[ 1.00000000e+00, -1.21566783e-16,  9.35031758e-17],
       [ 2.16426136e-16,  1.00000000e+00,  1.37539736e-16],
       [ 1.00203713e-15, -5.56970038e-16,  1.00000000e+00]])

## Numpy Linear Algebra

# A Story Problem: Computing Customer Lifetime

This example uses a Markov Model.  We will ignore many of the technical details for now. 

We will analyze a model of customer retention with linear algebra.  Assume that we have built a model of the life cycle of customers who shop on our company's Internet site.  Our model categorizes customers into one of four states:
- Purchased within the last month (Category 0)
- Last purchase was between within the last one to two months (Category 1)
- Last purchase was between within the last two to three months(Category 2)
- Has purchased previously, but not within the last three months (Category 3)

This categorization recognizes that different tactics, at differing levels of effort and cost, are required to entice customers in each category to make subsequent purchases.  It also recognizes that once customers fall into the last category it is extremely unlikely that they will ever again pruchase anything from the website.

We can build a matrix, $P$, whose rows and columns correspond to these four states, the elements of which correspond to the transition probability *from* the state associated with the row *to* the state associated with the column.

\begin{align}
P = \left[ 
\begin{array}{ccccc}
p_{00} & p_{01} & p_{02}& p_{03} \\
p_{10} & p_{11} & p_{12}& p_{13} \\
p_{20} & p_{21} & p_{22}& p_{23} \\
p_{30} & p_{31} & p_{32}& p_{33} 
\end{array}
\right]
\end{align}

where $p_{xy}$ is the probability of a customer transtioning from category/state $x$ to state $y$.  Notice that

\begin{align}
\Sigma_{j=0}^3 p_{ij}  = 1
\end{align}

for the probabilities in any row $i$ because a customer must transition to one of the categories.

The research question of interest to the company is, given a certain set of transition probabilities reflected in $P$, how many months will a customer be active, that is, before they fall into the last category from which they cannot be resurrected as a customer?  Let the column vector $n$ have an element for each state/category which,for each state, is the average number of months a customer remains active (before they fall into the last category) after they are categorized as being in that state.  Thus, $n$ has four elements and we have said, already, that $n_3=0$ once a customer reaches Category 3.  Our task is to solve for $n$.  Since we know already that $n_3=0$, we can ignore computing that element and we can also ignore the corresponding elements in $P$, which specifically are the last row and the last column.  Thus, redefine $P$ as

\begin{align}
P = \left[ 
\begin{array}{ccccc}
p_{00} & p_{01} & p_{02} \\
p_{10} & p_{11} & p_{12} \\
p_{20} & p_{21} & p_{22}
\end{array}
\right]
\end{align}

The solution for $n$ must satisfy these equations:

\begin{align}
n_0 = 1 + \sum_{i=0}^{2}{p_{0,i}n_i} \\
n_1 = 1 + \sum_{i=0}^{2}{p_{1,i}n_i} \\
n_2 = 1 + \sum_{i=0}^{2}{p_{2,i}n_i} 
\end{align}

If a customer is in any one of these states, we must add 1 month to their lifetime, as we do in the first term on the right-hand side of the equations.  Then, the customer transitons to one of the other states and experiences a remaining lifetime associated with that state, which is the second term on the right-hand side.  These are called a one-step equations.

We can gather these equations and write them in matrix-vector form, where $\textbf{1}$ is a vector of ones:

\begin{align}
n = \textbf{1} + Pn
\end{align}

This equation can be rewritten in a number of ways:

\begin{align}
\left(I - P \right) n = \textbf{1} \\
n = \left(I - P \right)^{-1} \textbf{1} 
\end{align}

**We will demonstrate three ways to find a solution to this problem using the linalg subpackage of numpy, and in so doing illustrate several numpy functions and methods.**

First, define the matrix $P$.

In [90]:
P = np.array([[0.3,0.7,0],[0.2,0.0,0.8],[0.1,0.0,0.0]])
P

array([[0.3, 0.7, 0. ],
       [0.2, 0. , 0.8],
       [0.1, 0. , 0. ]])

## Method 1: Use the numpy.linalg.solve() Function

The function <code>numpy.linalg.solve(A,b)</code> will solve equations of the form $A x = b$ yielding $x$ given the matrix $A$ and column vector $b$ as arguments.  The equation in the problem description, $\left(I - P \right) n = \textbf{1}$, is of that form.  This approach, reassuringly, yields the same result as the first approach.  

In [92]:
from numpy import linalg

In [93]:
linalg.solve((np.identity(P.shape[0]) - P),np.ones((P.shape[0],1)))

array([[4.48412698],
       [3.05555556],
       [1.4484127 ]])

## Method 2: Use the numpy.linalg.inv() Function to Compute the Inverse of a Matrix

This approach solves this form of the problem, $n = \left(I - P \right)^{-1} \textbf{1}$, but using <code>numpy.linalg.inv()</code> to take the inverse of $\left(I - P \right)$.  The <code>numpy.ndarray.dot()</code> method is, again, used for multiple a matrix by a vector.

In [94]:
linalg.inv(np.identity(P.shape[0]) - P).dot(np.ones((P.shape[0],1)))

array([[4.48412698],
       [3.05555556],
       [1.4484127 ]])

# <code>pandas</code>

<b>pan</b>el <b>da</b>ta