# <code>numpy</code>

<b>num</b>erical <b>py</b>thon

- Fast
- Data structures are limited to one data type
- Written in the C programming language

In [29]:
import numpy as np

## Numpy arrays (<code>ndarray</code>)

n-dimensional arrays

## Array Creation

In [30]:
a = np.array([0,1,2])
type(a), a

(numpy.ndarray, array([0, 1, 2]))

In [31]:
np.array((3,4,5))

array([3, 4, 5])

In [32]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(3,7)

array([3, 4, 5, 6])

In [36]:
# format: np.arange([start], stop, [step])
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [38]:
b.dtype

dtype('float64')

In [39]:
c = np.ones((2,3), dtype=np.int64)
c

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [40]:
np.ones((2,3)).astype(np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
d = np.ones((2,3))
print(d.dtype)
d = d.astype(np.int32)
print(d.dtype)

float64
int32


In [42]:
np.full((2,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [43]:
np.identity(6).astype(np.int16)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int16)

In [44]:
d.shape, type(d.shape)

((2, 3), tuple)

In [45]:
# number of rows
d.shape[0]

2

In [46]:
# number of columns
d.shape[1]

3

In [47]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        print(d[i][j])

1
1
1
1
1
1


In [51]:
d.flatten()

array([1, 1, 1, 1, 1, 1])

In [54]:
d.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [56]:
d.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [57]:
np.random.random((2,2))

array([[0.01601558, 0.56409307],
       [0.42340698, 0.7382894 ]])

In [66]:
np.random.randint(0, 9, (2,5))

array([[3, 2, 5, 2, 2],
       [4, 2, 0, 4, 0]])

## numpy Slices and Indexing

In [68]:
h = np.random.random((8,))
h

array([0.09270253, 0.77252393, 0.07615393, 0.10750887, 0.56920686,
       0.44419348, 0.10602389, 0.01271085])

In [71]:
j = np.random.random((7,7))
j

array([[0.84289947, 0.35398689, 0.9551968 , 0.7096073 , 0.13630193,
        0.65978114, 0.19054395],
       [0.4645478 , 0.91883729, 0.46641935, 0.52533993, 0.24641337,
        0.135258  , 0.56032224],
       [0.46924966, 0.01899494, 0.68333358, 0.3740239 , 0.40945611,
        0.65117585, 0.2638785 ],
       [0.66552858, 0.40071934, 0.51337696, 0.62863281, 0.14451895,
        0.93306593, 0.41697164],
       [0.24494242, 0.0845737 , 0.22411413, 0.70108488, 0.08040327,
        0.56551924, 0.58138612],
       [0.90659817, 0.98449794, 0.58519318, 0.12894619, 0.52829803,
        0.88909749, 0.28964525],
       [0.48063969, 0.1655322 , 0.24570394, 0.85272892, 0.31223758,
        0.77380359, 0.80363502]])

In [69]:
type((8,))

tuple

In [70]:
type((8))

int

In [72]:
print(h)
h[1:4]

[0.09270253 0.77252393 0.07615393 0.10750887 0.56920686 0.44419348
 0.10602389 0.01271085]


array([0.77252393, 0.07615393, 0.10750887])

In [75]:
h[1:7:2]

array([0.77252393, 0.10750887, 0.44419348])

SyntaxError: incomplete input (786403058.py, line 1)

In [73]:
j[2][3]

0.3740239015616935

In [74]:
j[2,3]

0.3740239015616935

In [78]:
j[1:6:2, 2]

array([0.46641935, 0.51337696, 0.58519318])

In [79]:
j[1:6, 2:4]

array([[0.46641935, 0.52533993],
       [0.68333358, 0.3740239 ],
       [0.51337696, 0.62863281],
       [0.22411413, 0.70108488],
       [0.58519318, 0.12894619]])

In [80]:
j[[1,2,3], [1,2,3]]

array([0.91883729, 0.68333358, 0.62863281])

## Array Methods and Calcuations

In [81]:
A = np.random.random((3,3))
A

array([[0.68124843, 0.41340898, 0.43512068],
       [0.86116854, 0.43759351, 0.6199251 ],
       [0.62583327, 0.59539012, 0.99054698]])

In [82]:
A.T

array([[0.68124843, 0.86116854, 0.62583327],
       [0.41340898, 0.43759351, 0.59539012],
       [0.43512068, 0.6199251 , 0.99054698]])

In [84]:
np.linalg.trans(A)

AttributeError: module 'numpy.linalg' has no attribute 'trans'

In [85]:
np.linalg.det(A)

-0.04447673974067723

In [88]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.44704045,  3.38231765, -1.48114771],
       [10.45621026, -9.04957473,  1.07046432],
       [-5.3706875 ,  3.30247893,  1.30191465]])

In [89]:
A.dot(Ainv)

array([[ 1.00000000e+00, -1.21566783e-16,  9.35031758e-17],
       [ 2.16426136e-16,  1.00000000e+00,  1.37539736e-16],
       [ 1.00203713e-15, -5.56970038e-16,  1.00000000e+00]])

## Numpy Linear Algebra

# A Story Problem: Computing Customer Lifetime

This example uses a Markov Model.  We will ignore many of the technical details for now. 

We will analyze a model of customer retention with linear algebra.  Assume that we have built a model of the life cycle of customers who shop on our company's Internet site.  Our model categorizes customers into one of four states:
- Purchased within the last month (Category 0)
- Last purchase was between within the last one to two months (Category 1)
- Last purchase was between within the last two to three months(Category 2)
- Has purchased previously, but not within the last three months (Category 3)

This categorization recognizes that different tactics, at differing levels of effort and cost, are required to entice customers in each category to make subsequent purchases.  It also recognizes that once customers fall into the last category it is extremely unlikely that they will ever again pruchase anything from the website.

We can build a matrix, $P$, whose rows and columns correspond to these four states, the elements of which correspond to the transition probability *from* the state associated with the row *to* the state associated with the column.

\begin{align}
P = \left[ 
\begin{array}{ccccc}
p_{00} & p_{01} & p_{02}& p_{03} \\
p_{10} & p_{11} & p_{12}& p_{13} \\
p_{20} & p_{21} & p_{22}& p_{23} \\
p_{30} & p_{31} & p_{32}& p_{33} 
\end{array}
\right]
\end{align}

where $p_{xy}$ is the probability of a customer transtioning from category/state $x$ to state $y$.  Notice that

\begin{align}
\Sigma_{j=0}^3 p_{ij}  = 1
\end{align}

for the probabilities in any row $i$ because a customer must transition to one of the categories.

The research question of interest to the company is, given a certain set of transition probabilities reflected in $P$, how many months will a customer be active, that is, before they fall into the last category from which they cannot be resurrected as a customer?  Let the column vector $n$ have an element for each state/category which,for each state, is the average number of months a customer remains active (before they fall into the last category) after they are categorized as being in that state.  Thus, $n$ has four elements and we have said, already, that $n_3=0$ once a customer reaches Category 3.  Our task is to solve for $n$.  Since we know already that $n_3=0$, we can ignore computing that element and we can also ignore the corresponding elements in $P$, which specifically are the last row and the last column.  Thus, redefine $P$ as

\begin{align}
P = \left[ 
\begin{array}{ccccc}
p_{00} & p_{01} & p_{02} \\
p_{10} & p_{11} & p_{12} \\
p_{20} & p_{21} & p_{22}
\end{array}
\right]
\end{align}

The solution for $n$ must satisfy these equations:

\begin{align}
n_0 = 1 + \sum_{i=0}^{2}{p_{0,i}n_i} \\
n_1 = 1 + \sum_{i=0}^{2}{p_{1,i}n_i} \\
n_2 = 1 + \sum_{i=0}^{2}{p_{2,i}n_i} 
\end{align}

If a customer is in any one of these states, we must add 1 month to their lifetime, as we do in the first term on the right-hand side of the equations.  Then, the customer transitons to one of the other states and experiences a remaining lifetime associated with that state, which is the second term on the right-hand side.  These are called a one-step equations.

We can gather these equations and write them in matrix-vector form, where $\textbf{1}$ is a vector of ones:

\begin{align}
n = \textbf{1} + Pn
\end{align}

This equation can be rewritten in a number of ways:

\begin{align}
\left(I - P \right) n = \textbf{1} \\
n = \left(I - P \right)^{-1} \textbf{1} 
\end{align}

**We will demonstrate three ways to find a solution to this problem using the linalg subpackage of numpy, and in so doing illustrate several numpy functions and methods.**

First, define the matrix $P$.

In [90]:
P = np.array([[0.3,0.7,0],[0.2,0.0,0.8],[0.1,0.0,0.0]])
P

array([[0.3, 0.7, 0. ],
       [0.2, 0. , 0.8],
       [0.1, 0. , 0. ]])

## Method 1: Use the numpy.linalg.solve() Function

The function <code>numpy.linalg.solve(A,b)</code> will solve equations of the form $A x = b$ yielding $x$ given the matrix $A$ and column vector $b$ as arguments.  The equation in the problem description, $\left(I - P \right) n = \textbf{1}$, is of that form.  This approach, reassuringly, yields the same result as the first approach.  

In [92]:
from numpy import linalg

In [93]:
linalg.solve((np.identity(P.shape[0]) - P),np.ones((P.shape[0],1)))

array([[4.48412698],
       [3.05555556],
       [1.4484127 ]])

## Method 2: Use the numpy.linalg.inv() Function to Compute the Inverse of a Matrix

This approach solves this form of the problem, $n = \left(I - P \right)^{-1} \textbf{1}$, but using <code>numpy.linalg.inv()</code> to take the inverse of $\left(I - P \right)$.  The <code>numpy.ndarray.dot()</code> method is, again, used for multiple a matrix by a vector.

In [94]:
linalg.inv(np.identity(P.shape[0]) - P).dot(np.ones((P.shape[0],1)))

array([[4.48412698],
       [3.05555556],
       [1.4484127 ]])

# <code>pandas</code>

<b>pan</b>el <b>da</b>ta

<code>pandas</code> data types:
- 1D: Series
- 2D: DataFrames
- 3D: Panels

Features:
- Each Series or DataFrame column is of a consistent data type
- Each DataFrame column can be of a different data type
- Each DataFrame column is built from a <code>numpy</code> array

Top (most used) five Python packages:
- __<code>numpy</code>__
- <code>scipy</code>
- __<code>Jupyter</code>__
- __<code>pandas</code>__
- __<code>matplotlib</code>__

## <code>pandas</code> Series

### A Series with Categorical Data

<code>pd.Series</code> performs a data type conversion, in the case below, from a Python list to a pandas Series data type.

In [95]:
import pandas as pd

In [96]:
ic = ['chocolate', 'strawberry', 'vanilla', 'rum raisin', 'chocolate', 'vanilla', 'vanilla', 'strawberry', 'rum raisin', 'chocolate', 'strawberry', 'cotton candy', 'chocolate', 'vanilla', 'rum raisin', 'vanilla', 'vanilla', 'strawberry', 'chocolate', 'vanilla', 'chocolate', 'vanilla', 'strawberry', 'vanilla', 'chocolate', 'chocolate', 'purple cow', 'chocolate', 'rum raisin', 'vanilla', 'chocolate', 'bubble gum', 'vanilla']
ic = pd.Series(ic)
ic

0        chocolate
1       strawberry
2          vanilla
3       rum raisin
4        chocolate
5          vanilla
6          vanilla
7       strawberry
8       rum raisin
9        chocolate
10      strawberry
11    cotton candy
12       chocolate
13         vanilla
14      rum raisin
15         vanilla
16         vanilla
17      strawberry
18       chocolate
19         vanilla
20       chocolate
21         vanilla
22      strawberry
23         vanilla
24       chocolate
25       chocolate
26      purple cow
27       chocolate
28      rum raisin
29         vanilla
30       chocolate
31      bubble gum
32         vanilla
dtype: object

In [97]:
type(ic)

pandas.core.series.Series

In [98]:
ic.head()

0     chocolate
1    strawberry
2       vanilla
3    rum raisin
4     chocolate
dtype: object

In [99]:
ic.head(n=3)

0     chocolate
1    strawberry
2       vanilla
dtype: object

### Series Structure

Series have one data column and an index "column."  The index column is generated automatically when you do the data type conversion, although you can manually change the data in the index column, which is meant primarily for accessing data in the values column and, perhaps, as labels for plotting the data.  The data in the "data" column are accessible with the .values property and the indices are available with the .index property.

In [100]:
ic.values

array(['chocolate', 'strawberry', 'vanilla', 'rum raisin', 'chocolate',
       'vanilla', 'vanilla', 'strawberry', 'rum raisin', 'chocolate',
       'strawberry', 'cotton candy', 'chocolate', 'vanilla', 'rum raisin',
       'vanilla', 'vanilla', 'strawberry', 'chocolate', 'vanilla',
       'chocolate', 'vanilla', 'strawberry', 'vanilla', 'chocolate',
       'chocolate', 'purple cow', 'chocolate', 'rum raisin', 'vanilla',
       'chocolate', 'bubble gum', 'vanilla'], dtype=object)

In [101]:
type(ic.values)

numpy.ndarray

In [102]:
ic.index

RangeIndex(start=0, stop=33, step=1)

In [103]:
ic.size

33

You can name your Series, if you wish.  The name will be shown when you print the Series.

In [104]:
ic.name = 'Flavor'

In [105]:
ic.name

'Flavor'

In [106]:
ic

0        chocolate
1       strawberry
2          vanilla
3       rum raisin
4        chocolate
5          vanilla
6          vanilla
7       strawberry
8       rum raisin
9        chocolate
10      strawberry
11    cotton candy
12       chocolate
13         vanilla
14      rum raisin
15         vanilla
16         vanilla
17      strawberry
18       chocolate
19         vanilla
20       chocolate
21         vanilla
22      strawberry
23         vanilla
24       chocolate
25       chocolate
26      purple cow
27       chocolate
28      rum raisin
29         vanilla
30       chocolate
31      bubble gum
32         vanilla
Name: Flavor, dtype: object

Collapse or expand the listing of the Series by clicking in the laft margin.

In [ ]:
ic

## Operations with Series

A very useful method for analyzing categorical data and plotting it, in a histogram, is the .value_counts() method.  It gives the number of observations found for each value in the data column.

In [107]:
ic.value_counts()

vanilla         11
chocolate       10
strawberry       5
rum raisin       4
cotton candy     1
purple cow       1
bubble gum       1
Name: Flavor, dtype: int64

In [108]:
type(ic.value_counts())

pandas.core.series.Series

In [109]:
ic.value_counts().index

Index(['vanilla', 'chocolate', 'strawberry', 'rum raisin', 'cotton candy',
       'purple cow', 'bubble gum'],
      dtype='object')

In [110]:
ic.value_counts().values

array([11, 10,  5,  4,  1,  1,  1], dtype=int64)

In [111]:
type(ic.value_counts().values)

numpy.ndarray

In [112]:
ic.unique()

array(['chocolate', 'strawberry', 'vanilla', 'rum raisin', 'cotton candy',
       'purple cow', 'bubble gum'], dtype=object)

### Accessing Series Data

Data rows can be accessed either by the 'label' in the index "column" or by their position in the data column.  The .loc command finds data rows based on their label and .iloc finds data based on it position, that is, the sequence in which the rows are found in the Series.  To start, the index column has values starting at 0 and incrementing by 1 with every subsequent row, so .loc and iloc will work identically.

In [113]:
import random
temp = pd.Series([random.random() for i in range(25)])
temp

0     0.931531
1     0.287781
2     0.695377
3     0.223280
4     0.081874
5     0.383196
6     0.863874
7     0.878258
8     0.649234
9     0.397767
10    0.026497
11    0.143870
12    0.707155
13    0.859273
14    0.619832
15    0.450022
16    0.045182
17    0.930076
18    0.539196
19    0.806883
20    0.991422
21    0.813460
22    0.760176
23    0.514939
24    0.020814
dtype: float64

In [114]:
temp.loc[0]

0.9315311598971022

In [115]:
temp.iloc[0]

0.9315311598971022

But, now, let's change the indices!

In [116]:
temp.index = range(50,75,1)

In [117]:
temp.index

RangeIndex(start=50, stop=75, step=1)

In [118]:
temp

50    0.931531
51    0.287781
52    0.695377
53    0.223280
54    0.081874
55    0.383196
56    0.863874
57    0.878258
58    0.649234
59    0.397767
60    0.026497
61    0.143870
62    0.707155
63    0.859273
64    0.619832
65    0.450022
66    0.045182
67    0.930076
68    0.539196
69    0.806883
70    0.991422
71    0.813460
72    0.760176
73    0.514939
74    0.020814
dtype: float64

The statement below will yield an error since we no long have an index label of 0.

In [119]:
temp.loc[0]

KeyError: 0

The first record, now, has a label of 51.

In [121]:
temp.loc[50]

0.9315311598971022

In [120]:
temp.iloc[0]

0.9315311598971022

### Series Methods for Numerical Data

In [122]:
print('temp.sum(): ',temp.sum())
print('temp.mean(): ',temp.mean())
print('temp.median(): ',temp.median())
print('temp.product(): ',temp.product())
print('\ntemp.describe(): \n',temp.describe())


temp.sum():  13.620966906566
temp.mean():  0.54483867626264
temp.median():  0.6198317384601386
temp.product():  1.9859720305234757e-11

temp.describe(): 
 count    25.000000
mean      0.544839
std       0.319969
min       0.020814
25%       0.287781
50%       0.619832
75%       0.813460
max       0.991422
dtype: float64


In [127]:
temp.sort_values()
temp.head()

74    0.020814
60    0.026497
66    0.045182
54    0.081874
61    0.143870
dtype: float64

The inplace argument causes the contents of the Series to be replaced with the sorted version.

In [128]:
temp.sort_values(inplace=True)
temp.head()

74    0.020814
60    0.026497
66    0.045182
54    0.081874
61    0.143870
dtype: float64

Oops, the command above did not change the series.  The Series is not altered unless we set the 'inplace' parameter equal to True. 

In [126]:
saveIt = temp.sort_values()
saveIt

74    0.020814
60    0.026497
66    0.045182
54    0.081874
61    0.143870
53    0.223280
51    0.287781
55    0.383196
59    0.397767
65    0.450022
73    0.514939
68    0.539196
64    0.619832
58    0.649234
52    0.695377
62    0.707155
72    0.760176
69    0.806883
71    0.813460
63    0.859273
56    0.863874
57    0.878258
67    0.930076
50    0.931531
70    0.991422
dtype: float64

In [ ]:
temp.sort_values(inplace=True)
temp.head()

Use the ascending parameter to sort in descending order.

In [ ]:
temp.sort_values(inplace=True,ascending=False)
temp.head()

You can use the command below to put the data back in their original order, by index, if your indices are sequential integers.

In [129]:
temp.sort_index(inplace=True)
temp.head()

50    0.931531
51    0.287781
52    0.695377
53    0.223280
54    0.081874
dtype: float64

## <code>pandas DataFrame</code>s

### Inputting Text Files with pandas

The pd.read_csv() method is very useful for inputting csv files.  The first row should contain the names of the columns.

In the cell below we are reading in the contents of a file that contains the Iris data that we previously worked with and assigning that data to the variable df.  Using df or using variable names starting with df is a good technique to help remind you that the data type of the variable is a DataFrame.

In [133]:
df = pd.read_csv('Iris.csv')
print('Type of df variable: ',type(df))
print('Column Labels: ',df.columns.values)

Type of df variable:  <class 'pandas.core.frame.DataFrame'>
Column Labels:  ['Id' 'SepalLengthCm' 'SepalWidthCm' 'PetalLengthCm' 'PetalWidthCm'
 'Species']


### Accessing DataFrame Elements

In [134]:
df['PetalLengthCm']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

In [ ]:
df['PetalWidthCm']

In [135]:
type(df['PetalLengthCm'])

pandas.core.series.Series

In [136]:
df.loc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [137]:
df.iloc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [138]:
df['PetalWidthCm'].iloc[0]

0.2

In [139]:
df.iloc[0]['PetalWidthCm']

0.2

### Properties and Methods to DataFrame Columns

Many of the same properties that we applied to pandas Series also apply to pandas DataFrames.

In [140]:
df.shape

(150, 6)

In [141]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [142]:
df.values

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 

In [ ]:
df.index

In [143]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [144]:
df.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species'], dtype=object)

In [145]:
df.values.tolist()

[[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
 [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
 [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
 [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
 [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
 [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
 [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
 [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
 [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
 [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
 [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
 [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
 [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
 [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
 [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
 [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
 [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
 [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
 [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
 [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
 [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 [22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
 [23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
 [24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
 

In [146]:
type(df.values.tolist())

list

In [ ]:
df.columns.values.tolist()

In [147]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [148]:
df.mean()

C:\Users\jrbrad\AppData\Local\Temp\ipykernel_15200\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [149]:
df.median()

C:\Users\jrbrad\AppData\Local\Temp\ipykernel_15200\530051474.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()


Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [150]:
df.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm             2.0
PetalLengthCm            1.0
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [151]:
df.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

Here is a link that shows other mathematical functions that can be applied to DataFrames:

[https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)

### Applying Series Properties and Methods to DataFrame Columns

The columns of a DataFrame are Series objects, so you can apply the Series properties and methods that we have descussed previously.

In [ ]:
df['PetalLengthCm'].loc[0]

In [ ]:
df['PetalLengthCm'].iloc[0]

In [ ]:
print(df['PetalLengthCm'].sum())
print(df['PetalLengthCm'].mean())
print(df['PetalLengthCm'].median())
print(df['PetalLengthCm'].shape)
print(df['PetalLengthCm'].describe())

In [ ]:
df['PetalLengthCm'].values

In [ ]:
df['PetalLengthCm'].index

In [ ]:
df['PetalLengthCm'].size

In [153]:
df['PetalLengthCm'].name

'PetalLengthCm'

In [ ]:
df['Species'].unique()

In [ ]:
df['Species'].value_counts()

### Sorting DataFrame Rows

In [154]:
df.sort_values(by='SepalLengthCm',inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
42    43            4.4           3.2            1.3           0.2   
38    39            4.4           3.0            1.3           0.2   
8      9            4.4           2.9            1.4           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   
117  118            7.7           3.8            6.7           2.2   
135  136            7.7           3.0            6.1           2.3   
131  132            7.9           3.8            6.4           2.0   

            Species  
13      Iris-setosa  
42      Iris-setosa  
38      Iris-setosa  
8       Iris-setosa  
41      Iris-setosa  
..              ...  
122  Iris-virginica  
118  Iris-virginica  
117  Iris-virginica  
135  Iris-virginica  
131  Iris-virginica  

[150 rows x 6 columns]

In [155]:
df.sort_index(inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [156]:
df.sort_values(by=['SepalLengthCm','SepalWidthCm'], inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   

            Species  
13      Iris-setosa  
8       Iris-setosa  
38      Iris-setosa  
42      Iris-setosa  
41      Iris-setosa  
..              ...  
118  Iris-virginica  
122  Iris-virginica  
135  Iris-virginica  
117  Iris-virginica  
131  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
df.sort_values(by='Id',inplace=True)
df

### Creating and Deleting New DataFrame Columns and Deleting Existing Columns

Feature Engineering is a name for creating new columns that enhance the value of your analysis by, for example, increasing the accuracy of predictions.  We will demonstrate how to create new columns in a pandas DataFrame, although the task we will perform is not of monumental value.  Specifically, we will create a new column that converts the data from being measured in centimeters to being measures in inches.

Let's convert the PetalLengthCm column to inches and, in so doing, create a new column called PetalLengthIn.

The statement in the cell below is, perhaps, a bit confusing.  It seems that we are dividing a dataFrame column, on the right-hand side, by a constant.  Thus, it seems we've mixed data type: we have a pandas Series and a constant.  However, the division is interpreted element-wise, so each element is divided by 2.54.

In [157]:
InPerCm = 2.54   # Conversion factor for inches to centimeters
df['PetalLengthIn'] = df['PetalLengthCm'] / InPerCm
df['PetalLengthIn']

13     0.433071
8      0.551181
38     0.511811
42     0.511811
41     0.511811
         ...   
118    2.716535
122    2.637795
135    2.401575
117    2.637795
131    2.519685
Name: PetalLengthIn, Length: 150, dtype: float64

Recall that we previously saw that we might predict Iris species based on the PetalLengthIn dimension, which is the column we just created.  Recall that a PetalLengthIn less than 1 inch indicated Iris-setosa, a PetalLengthIn between 1 and 1.9 inches suggests Iris-versicolor, and a PetalLengthIn greater than 1.9 suggests Iris-virginica.

Let's create a column with these predictions.  The first step is to create a function that, given a row from the DataFrame df, evaluates the value in the PetalLengthIn column and returns the appropriate species names as a string value.

In [159]:
def predict(row):
    if row['PetalLengthIn'] <= 1.0:
        return 'Iris-setosa'
    elif row['PetalLengthIn'] <= 1.9:
        return 'Iris-versicolor'
    else:
        return 'Iris-virginica'

The .apply DataFrame method causes these actions:

- Each row of the Dataframe is passed, one-by-one, to the function whose name is given as the first argument.  In this case the function name is predict, which is the function we just defined.
- The return value from the predict function for each row is appended to the new column 'Predict' in the same row that gave rise to the return value.
- The 'axis' argument determines whether the DataFrame data is sent to 'predict' by rows or by columns.

This last point is, perhaps, a bit confusing.  Specifying axis = 'columns' means that one 'set' of column values are sent to the function in each pass.  That means, by the way I think, that the data are sent row by row.  Specifying axis = 'rows' implies the converse: the total contents of each column, including the index column, are sent one-by-one to the function.

In [160]:
df['Predict'] = df.apply(predict,axis='columns')
print(df['Predict'])

13        Iris-setosa
8         Iris-setosa
38        Iris-setosa
42        Iris-setosa
41        Iris-setosa
            ...      
118    Iris-virginica
122    Iris-virginica
135    Iris-virginica
117    Iris-virginica
131    Iris-virginica
Name: Predict, Length: 150, dtype: object


In [161]:
df['DeleteMe'] = 0
df['DeleteMe1'] = 0
df['DeleteMe2'] = 0

In [164]:
df.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species', 'PetalLengthIn', 'Predict', 'DeleteMe',
       'DeleteMe1', 'DeleteMe2'], dtype=object)

In [165]:
df.drop('DeleteMe', axis=1, inplace=True)

In [166]:
df.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species', 'PetalLengthIn', 'Predict', 'DeleteMe1',
       'DeleteMe2'], dtype=object)

In [ ]:
df.drop(['DeleteMe1','DeleteMe2'], axis=1, inplace=True)

### Handling Null Fields

In [167]:
import numpy as np
dfAdd = pd.DataFrame([[151,5.0,17,1.4,0.2,np.NaN,0.57,np.NaN],[152,5.0,18,1.4,0.2,np.NaN,0.57,np.NaN]], columns=['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
 'Species', 'PetalLengthIn', 'Predict'])

In [168]:
dfAdd

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species  \
0  151            5.0            17            1.4           0.2      NaN   
1  152            5.0            18            1.4           0.2      NaN   

   PetalLengthIn  Predict  
0           0.57      NaN  
1           0.57      NaN

In [169]:
df = df.append(dfAdd)

C:\Users\jrbrad\AppData\Local\Temp\ipykernel_15200\558829623.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfAdd)


In [170]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   
0    151            5.0          17.0            1.4           0.2   
1    152            5.0          18.0            1.4           0.2   

            Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
13      Iris-setosa       0.433071     Iris-setosa        0.0        0.0  
8       Iris-setosa       0.551181     Iris-setosa        0.0        0.0  
38      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
42      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
41      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
..              ...            ...             ...        ...        ...  
135  Iris-virginica       2.401575  Iris-virginica        0.0        0.0  
117  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
131  Iris-virginica       2.519685  Iris-virginica        0.0        0.0  
0               NaN       0.570000             NaN        NaN        NaN  
1               NaN       0.570000             NaN        NaN        NaN  

[152 rows x 10 columns]

In [171]:
df.dropna(inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   

            Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
13      Iris-setosa       0.433071     Iris-setosa        0.0        0.0  
8       Iris-setosa       0.551181     Iris-setosa        0.0        0.0  
38      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
42      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
41      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
..              ...            ...             ...        ...        ...  
118  Iris-virginica       2.716535  Iris-virginica        0.0        0.0  
122  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
135  Iris-virginica       2.401575  Iris-virginica        0.0        0.0  
117  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
131  Iris-virginica       2.519685  Iris-virginica        0.0        0.0  

[150 rows x 10 columns]

In [174]:
dfAdd = pd.DataFrame([[151,5.0,17,1.4,0.2,np.NaN,0.57,np.NaN],[152,5.0,18,1.4,0.2,np.NaN,0.57,np.NaN]], columns=['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
 'Species', 'PetalLengthIn', 'Predict'])
df = df.append(dfAdd)
df

C:\Users\jrbrad\AppData\Local\Temp\ipykernel_15200\1650249893.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfAdd)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
131  132            7.9           3.8            6.4           2.0   
0    151            5.0          17.0            1.4           0.2   
1    152            5.0          18.0            1.4           0.2   
0    151            5.0          17.0            1.4           0.2   
1    152            5.0          18.0            1.4           0.2   

            Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
13      Iris-setosa       0.433071     Iris-setosa        0.0        0.0  
8       Iris-setosa       0.551181     Iris-setosa        0.0        0.0  
38      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
42      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
41      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
..              ...            ...             ...        ...        ...  
131  Iris-virginica       2.519685  Iris-virginica        0.0        0.0  
0      NotSpecified       0.570000             NaN        NaN        NaN  
1      NotSpecified       0.570000             NaN        NaN        NaN  
0               NaN       0.570000             NaN        NaN        NaN  
1               NaN       0.570000             NaN        NaN        NaN  

[154 rows x 10 columns]

In [173]:
df['Species'].fillna('NotSpecified',inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   
0    151            5.0          17.0            1.4           0.2   
1    152            5.0          18.0            1.4           0.2   

            Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
13      Iris-setosa       0.433071     Iris-setosa        0.0        0.0  
8       Iris-setosa       0.551181     Iris-setosa        0.0        0.0  
38      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
42      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
41      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
..              ...            ...             ...        ...        ...  
135  Iris-virginica       2.401575  Iris-virginica        0.0        0.0  
117  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
131  Iris-virginica       2.519685  Iris-virginica        0.0        0.0  
0      NotSpecified       0.570000             NaN        NaN        NaN  
1      NotSpecified       0.570000             NaN        NaN        NaN  

[152 rows x 10 columns]

In [175]:
df.dropna(subset = ['Predict'],inplace=True)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
8      9            4.4           2.9            1.4           0.2   
38    39            4.4           3.0            1.3           0.2   
42    43            4.4           3.2            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   

            Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
13      Iris-setosa       0.433071     Iris-setosa        0.0        0.0  
8       Iris-setosa       0.551181     Iris-setosa        0.0        0.0  
38      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
42      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
41      Iris-setosa       0.511811     Iris-setosa        0.0        0.0  
..              ...            ...             ...        ...        ...  
118  Iris-virginica       2.716535  Iris-virginica        0.0        0.0  
122  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
135  Iris-virginica       2.401575  Iris-virginica        0.0        0.0  
117  Iris-virginica       2.637795  Iris-virginica        0.0        0.0  
131  Iris-virginica       2.519685  Iris-virginica        0.0        0.0  

[150 rows x 10 columns]

### Filtering DataFrame Rows

An analyst sometimes must look at a subset of the rows in a data source.  The pandas package offers an easy way to _filter_  out the rows that we need to omit from a computation.

Filtering out rows requires that we reference the DataFrame of interest and put a logical condition within square bracket that indicates the condition for the rows to retain in the DataFrame, such as:

df[ _condition_ ]

If we want to replace the DataFrame with the filtered set of rows, then we need this assignment statement:

df = df[ _condition_ ]

We may use multiple conditions where | indicates a logical OR operator and & indicates a logical AND operator:

df = df[ _(condition1) | (condition2)_ ]

df = df[ _(condition1) & (condition2)_ ]

Note the Boolean condition statements must be enclosed in parentheses to enure the conditional statements are parsed in the desired order.

In [ ]:
df.shape

In [ ]:
df.columns.values

Let's first focus on the rows where the petal lenght is 5.0 cm or greater.

In [176]:
df['PetalLengthCm'] >= 5.0

13     False
8      False
38     False
42     False
41     False
       ...  
118     True
122     True
135     True
117     True
131     True
Name: PetalLengthCm, Length: 150, dtype: bool

In [179]:
df[df['PetalLengthCm'] >= 5.0]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
113  114            5.7           2.5            5.0           2.0   
101  102            5.8           2.7            5.1           1.9   
142  143            5.8           2.7            5.1           1.9   
114  115            5.8           2.8            5.1           2.4   
149  150            5.9           3.0            5.1           1.8   
119  120            6.0           2.2            5.0           1.5   
83    84            6.0           2.7            5.1           1.6   
134  135            6.1           2.6            5.6           1.4   
148  149            6.2           3.4            5.4           2.3   
146  147            6.3           2.5            5.0           1.9   
133  134            6.3           2.8            5.1           1.5   
103  104            6.3           2.9            5.6           1.8   
100  101            6.3           3.3            6.0           2.5   
136  137            6.3           3.4            5.6           2.4   
111  112            6.4           2.7            5.3           1.9   
128  129            6.4           2.8            5.6           2.1   
132  133            6.4           2.8            5.6           2.2   
137  138            6.4           3.1            5.5           1.8   
115  116            6.4           3.2            5.3           2.3   
104  105            6.5           3.0            5.8           2.2   
116  117            6.5           3.0            5.5           1.8   
147  148            6.5           3.0            5.2           2.0   
110  111            6.5           3.2            5.1           2.0   
108  109            6.7           2.5            5.8           1.8   
77    78            6.7           3.0            5.0           1.7   
145  146            6.7           3.0            5.2           2.3   
140  141            6.7           3.1            5.6           2.4   
124  125            6.7           3.3            5.7           2.1   
144  145            6.7           3.3            5.7           2.5   
112  113            6.8           3.0            5.5           2.1   
143  144            6.8           3.2            5.9           2.3   
139  140            6.9           3.1            5.4           2.1   
141  142            6.9           3.1            5.1           2.3   
120  121            6.9           3.2            5.7           2.3   
102  103            7.1           3.0            5.9           2.1   
129  130            7.2           3.0            5.8           1.6   
125  126            7.2           3.2            6.0           1.8   
109  110            7.2           3.6            6.1           2.5   
107  108            7.3           2.9            6.3           1.8   
130  131            7.4           2.8            6.1           1.9   
105  106            7.6           3.0            6.6           2.1   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
135  136            7.7           3.0            6.1           2.3   
117  118            7.7           3.8            6.7           2.2   
131  132            7.9           3.8            6.4           2.0   

             Species  PetalLengthIn         Predict  DeleteMe1  DeleteMe2  
113   Iris-virginica       1.968504  Iris-virginica        0.0        0.0  
101   Iris-virginica       2.007874  Iris-virginica        0.0        0.0  
142   Iris-virginica       2.007874  Iris-virginica        0.0        0.0  
114   Iris-virginica       2.007874  Iris-virginica        0.0        0.0  
149   Iris-virginica       2.007874  Iris-virginica        0.0        0.0  
119   Iris-virginica       1.968504  Iris-virginica        0.0        0.0  
83   Iris-versicolor       2.007874  Iris-virginica        0.0        0.0  
134   Iris-virginica       2.204724  Iris-virginica        0.0        0.0  
148   Iris-virginica       2.12

In [180]:
df.shape

(150, 10)

In [181]:
df = df[df['PetalLengthCm'] >= 5.0]

In [182]:
df.shape

(46, 10)

Let's reload the original DataFrame.

In [183]:
df = pd.read_csv('Iris.csv')

In [ ]:
df.shape

Let's consider a situation where we want to compute statistics on the observations where the petal length is 5.0 cm or greater adn the petal width is less than 2.0 cm.  Again, note the parentheses that are needed around each of the two conditions.

In [184]:
df = df[(df['PetalLengthCm'] >= 5.0) & (df['PetalWidthCm'] < 2.0)]

In [185]:
df.shape

(18, 6)

In [ ]:
df